sonar.projectKey=darioegb_ng-prevent-cut-copy-paste
sonar.organization=darioegb-1
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=projects/**/*.spec.ts, projects/**/*.js, projects/ng-prevent-cut-copy-paste-showcase/**
